### ISSUE TITLE
想请教一下如何关闭对话

### ISSUE THREAD

**Issue by Brhiza** [stevenjoezhang/live2d-widget#29]

**Comment by stevenjoezhang** [comment]
加一行 CSS
```css
#waifu-tips {
    display: none !important;
}
```
