### ISSUE TITLE
怎么把看板娘的位置移到右面？

### ISSUE THREAD

**Issue by fangaso** [stevenjoezhang/live2d-widget#76]
**怎么把看板娘的位置移到右面？需要修改那个文件？谢谢啦！**

**Comment by KnowsCount** [comment]
在 `waifu.css` 中找到 `#waifu`，并将其修改成：

```css
#waifu {
	bottom: -1000px;
	right: 0;
	line-height: 0;
	margin-bottom: -10px;
	position: fixed;
	transform: translateY(3px);
	transition: transform .3s ease-in-out, bottom 3s ease-in-out;
	z-index: 1;
}
```
